services:

  grafanaprometheustest:
      container_name: GrafanaPrometheusTest
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
      ports:
        - "5000:80"
      networks:
        - myappnetwork

networks:
  myappnetwork:
    name: myappnetwork
    driver: bridge